# Extra autostart processes
# exec-once = uwsm app -- my-service

# Start 1Password silently on boot
exec-once = 1password --silent

# Start clipboard manager
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
